apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: pp.order.events
  namespace: pizza-pulse
  labels:
    strimzi.io/cluster: pp-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
    retention.bytes: 1073741824
    segment.bytes: 268435456
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: pp.demand.predictions
  namespace: pizza-pulse
  labels:
    strimzi.io/cluster: pp-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
    retention.bytes: 1073741824
    segment.bytes: 268435456
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: pp.ingredient.alerts
  namespace: pizza-pulse
  labels:
    strimzi.io/cluster: pp-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
    retention.bytes: 1073741824
    segment.bytes: 268435456
